---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/api/v1/parking_lots":
    get:
      summary: Get all parking_lots
      tags:
      - Parking Lots
      responses:
        '200':
          description: parking_lots found
        '401':
          description: unauthorized
    post:
      summary: Create a parking_lot
      tags:
      - Parking Lots
      responses:
        '302':
          description: redirected
        '401':
          description: unauthorized
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                parking_lot:
                  properties:
                    name:
                      type: string
                    flat_rate:
                      type: number
                    whole_day_flat_rate:
                      type: number
              required:
              - name
              - flat_rate
              - whole_day_flat_rate
          application/xml:
            schema:
              type: object
              properties:
                parking_lot:
                  name:
                    type: string
                  flat_rate:
                    type: number
                  whole_day_flat_rate:
                    type: number
              required:
              - name
              - flat_rate
              - whole_day_flat_rate
          application/xml:
  "/api/v1/parking_lots/{id}":
    get:
      summary: Get a parking_lot
      tags:
      - Parking Lot
      parameters:
      - name: id
        in: path
        required: true
        description: ID of the parking_lot
        schema:
          type: string
      responses:
        '200':
          description: parking_lot found
        '404':
          description: parking_lot not found
        '401':
          description: unauthorized
  "/api/v1/parking_lots/{parking_lot_id}/park":
    post:
      summary: Park a Vehicle
      tags:
      - Parking Lot
      parameters:
      - name: parking_lot_id
        in: path
        required: true
        description: ID of the parking_lot
        schema:
          type: string
      responses:
        '200':
          description: parking_lot found
        '404':
          description: parking_lot not found
        '401':
          description: unauthorized
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                parking_info:
                  type: object
                  properties:
                    type:
                      type: string
                      enum:
                        - small
                        - medium
                        - large
                    plate_no:
                      type: string
                    accessway_id:
                      type: number
                    parking_lot_id:
                      type: number
              required:
              - type
              - plate_no
              - accessway_id
              - parking_lot_id
          application/xml:
            schema:
              type: object
              properties:
                type:
                  type: string
                  enum:
                    - small
                    - medium
                    - large
                plate_no:
                  type: string
                accessway_id:
                  type: number
                parking_lot_id:
                  type: number
              required:
              - type
              - plate_no
              - accessway_id
              - parking_lot_id
  "/api/v1/parking_lots/{parking_lot_id}/unpark":
    post:
      summary: Unpark a Vehicle
      tags:
      - Parking Lot
      parameters:
      - name: parking_lot_id
        in: path
        required: true
        description: ID of the parking_lot
        schema:
          type: string
      responses:
        '200':
          description: parking_lot found
        '404':
          description: parking_lot not found
        '401':
          description: unauthorized
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                ticket_id:
                  type: number
              required:
              - ticket_id
          application/xml:
            schema:
              type: object
              properties:
                parking_lot_id:
                  type: number
              required:
              - ticket_id
  "/api/v1/parking_lots/{parking_lot_id}/create_parking_slots":
    post:
      summary: Upload csv to populate parking slots
      tags:
      - Parking Slots
      parameters:
        - in: path 
          name: parking_lot_id
          required: true
          description: ID of the parking_lot
          schema:
            type: string
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                parking_slots_file:
                  type: string
                  format: binary
      responses:
        '200':
          description: parking_lot found
        '404':
          description: parking_lot not found
        '422':
          description: Unprocessable Entity
        '401':
          description: unauthorized
  "/api/v1/parking_lots/{parking_lot_id}/add_accessways":
    post:
      summary: Upload csv to add accessways and distance to parking slots
      tags:
      - Parking Lot accessways and slot distance
      parameters:
        - in: path 
          name: parking_lot_id
          required: true
          description: ID of the parking_lot
          schema:
            type: string
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                accessways_and_distance_file:
                  type: string
                  format: binary
      responses:
        '200':
          description: parking_lot found
        '404':
          description: parking_lot not found
        '422':
          description: Unprocessable Entity
        '401':
          description: unauthorized
servers:
- url: http://{defaultHost}
  variables:
    defaultHost:
      default: localhost:3000
components:
  securitySchemes:
    bearerAuth:            # arbitrary name for the security scheme
      type: http
      scheme: bearer
      bearerFormat: JWT  
security:
  - bearerAuth: [] 